apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: cybershop/client:development
          imagePullPolicy: "Always"
          securityContext:
            allowPrivilegeEscalation: false
          resources:
            limits:
              cpu: 500m
              memory: 536Mi
          volumeMounts:
            - mountPath: /tmp
              name: tmp
          env:
            - name: TMPDIR
              value: /tmp
            - name: NEXT_PUBLIC_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NEXT_PUBLIC_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NEXT_PUBLIC_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: client-id-secret
                  key: CLIENT_ID
            - name: NEXT_PUBLIC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: client-secret-secret
                  key: CLIENT_SECRET
            - name: NEXT_PUBLIC_TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: tenant-id-secret
                  key: TENANT_ID
            - name: NEXT_PUBLIC_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: encryption-key-secret
                  key: ENCRYPTION_KEY
            - name: NEXT_PUBLIC_RESPONSE_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: response-encryption-key-secret
                  key: RESPONSE_ENCRYPTION_KEY
            - name: NEXT_PUBLIC_DOMAIN_URL
              value: https://phoenix.local
            - name: NEXT_PUBLIC_REDIRECT_URI
              value: https://phoenix.local/login
      imagePullSecrets:
        - name: docker-regcred
      volumes:
        - emptyDir: {}
          name: tmp
---
apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  selector:
    app: client
  ports:
    - name: client
      protocol: TCP
      port: 3000
      targetPort: 3000
