apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
        - name: chat
          image: moxfive/chat:development
          imagePullPolicy: "Always"
          securityContext:
            allowPrivilegeEscalation: false
          resources:
            limits:
              cpu: 1000m
              memory: 1024Mi
          volumeMounts:
            - mountPath: /tmp
              name: tmp
#            - name: data
#              mountPath: /uploads
#            - name: data
#              mountPath: /exports
#            - name: data
#              mountPath: /sample
          env:
            - name: TMPDIR
              value: /tmp
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-uri-secret
                  key: MONGO_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
            - name: COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: cookie-secret-secret
                  key: COOKIE_SECRET
            - name: MOXFIVE_ID
              valueFrom:
                secretKeyRef:
                  name: moxfive-id-secret
                  key: MOXFIVE_ID
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: client-id-secret
                  key: CLIENT_ID
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: client-secret-secret
                  key: CLIENT_SECRET
            - name: TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: tenant-id-secret
                  key: TENANT_ID
            - name: ENTERPRISE_OBJECT_ID
              valueFrom:
                secretKeyRef:
                  name: enterprise-object-id-secret
                  key: ENTERPRISE_OBJECT_ID
            - name: SUPER_ADMIN_POLICY_ID
              valueFrom:
                secretKeyRef:
                  name: super-admin-policy-id-secret
                  key: SUPER_ADMIN_POLICY_ID
            - name: AZURE_STORAGE_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: azure-storage-connection-string-secret
                  key: AZURE_STORAGE_CONNECTION_STRING
            - name: DOMAIN_URL
              value: https://phoenix.local
            - name: LOCAL_ENVIRONMENT
              value: "true"
      imagePullSecrets:
        - name: docker-regcred
      volumes:
        - emptyDir: {}
          name: tmp
#        - name: data
#          persistentVolumeClaim:
#            claimName: chat-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: chat-srv
spec:
  selector:
    app: chat
  ports:
    - name: chat
      protocol: TCP
      port: 3000
      targetPort: 3000
