apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-depl-1
  namespace: default
spec:
  serviceName: redis-1
  replicas: 1
  selector:
    matchLabels:
      app: redis-1
  template:
    metadata:
      labels:
        app: redis-1
    spec:
      containers:
        - name: redis
          image: redis:6.2.3-alpine
          command: ["redis-server"]
          volumeMounts:
          - name: data
            mountPath: /var/lib/redis
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: redis-pv-claim-1
---
apiVersion: v1
kind: Service
metadata:
  name: redis-srv-1
spec:
  selector:
    app: redis-1
  ports:
    - name: client
      protocol: TCP
      port: 6379
      targetPort: 6379
