# apiVersion: skaffold/v2alpha3
# kind: Config
# deploy:
#   kubectl:
#     manifests:
#       - ./infra/k8s-local/*
# build:
#   local:
#     push: false
#   tagPolicy:
#     envTemplate:
#       template: "{{.NODE_ENV}}"
#   artifacts:
#     - image: moxfive/authentication
#       context: authentication
#       docker:
#         dockerfile: Dockerfile_local
#         buildArgs:
#           GITHUB_TOKEN: "{{.GITHUB_TOKEN}}"
#       sync:
#         infer:
#           - "**/*.ts"
# profiles:
#   - name: local
# #      - op: replace
# #        path: /build/artifacts/3/docker/dockerfile
# #        value: Dockerfile_local
#     activation:
#       - env: NODE_ENV=local
