"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NotificationWrapper from "@/lib/notification/notification";
import ReduxProvider from "@/store/redux-provider";
import Navbar from "./navbar";
import { usePathname } from "next/navigation";
// import CheckLogin from "@/shared/components/check-login";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();

  // Check if the current route starts with "/account-security"
  const isAccountSecurityRoute = !pathname.startsWith("/account-security");

  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <NotificationWrapper />
          {/* <CheckLogin/> */}

          {/* <div className="flex h-screen">
            {isAccountSecurityRoute && (
              <div className="w-1/5">
                <Navbar />
              </div>
            )}
            <div className={`bg-gray-100 ${isAccountSecurityRoute ? 'w-4/5' : 'w-full'} overflow-auto`}>
              {children}
            </div>
          </div> */}
          <div className="min-h-screen">
            {isAccountSecurityRoute && (
              <div className="fixed top-0 left-0 right-0 z-10 bg-white border-b">
                <Navbar />
              </div>
            )}
            <div className={`${isAccountSecurityRoute ? 'pt-16' : ''} min-h-screen bg-gray-100`}>
              {children}
            </div>
          </div>

          {/* Runtime classes are not generated so, need to specify here */}
          <span className="text-xs text-red-800 pt-0 bg-opacity-80 hidden">
          </span>
        </ReduxProvider>
      </body>
    </html >
  );
}
